# spring Config
spring:
  datasource:
    url: jdbc:sqlite:/www/wwwroot/0.0.0.0/mmkpark.db
    driver-class-name: org.sqlite.JDBC
    username:
    password:
  servlet:
    multipart:
      max-file-size: 5MB
      max-request-size: 5MB
  resources:
    static-locations: classpath:/templates/,classpath:/META-INF/resources/,classpath:/resources/,classpath:/static/,classpath:/public/
  mvc:
    static-path-pattern: /static/**

# 上传文件存放位置
prop:
  upload-folder: /www/wwwroot/0.0.0.0/pic/


mybatis-plus:
  mapper-locations: classpath*:/mapper/**Mapper.xml
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
server:
  port: 8088

shiro-redis:
  enabled: true
  redis-manager:
    host: 127.0.0.1:6379
    timeout: 5000

mmk:
  jwt:
    secret: f4e2e52034348f86b67cde581c0f9eb5
    expire: 604800
    header: Authorization

# Mqtt配置
mqtt:
  client:
    username:
    password:
    serverURIs: tcp://127.0.0.1:1883 # 客户端地址，多个使用逗号隔开
    clientId: ${random.value}    # ${random.value}随机字符串
    keepAliveInterval: 30
    connectionTimeout: 30
  producer:
    defaultQos: 1
    defaultRetained: true
    defaultTopic: defaultTopicName
  consumer:
    defaultQos: 1
    completionTimeout: 30000
    consumerTopics: state,cvcar,piserial,pypub # 监听的 topic，多个使用逗号隔开
